# Generated by Django 4.2.8 on 2023-12-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='titulo')),
                ('completed', models.BooleanField(default=False, verbose_name='compelto?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
        ),
    ]
